name: Deploy scrbd-downloader Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js app
      run: npm run build
      
    - name: ✅ VERIFY BUILD - Check if .next folder exists
      run: |
        echo "=== BUILD VERIFICATION ==="
        if [ -d ".next" ]; then
          echo "✅ .next folder EXISTS"
          ls -la .next/ | head -10
          echo "Total files in .next: $(find .next -type f | wc -l)"
        else
          echo "❌ .next folder MISSING - Build failed!"
          exit 1
        fi
        
    - name: ✅ VERIFY FILES - List all files to be copied
      run: |
        echo "=== FILES TO BE COPIED ==="
        echo "📁 .next folder:"
        ls -la .next/ | head -5
        echo "📄 package.json:" && ls -la package.json
        echo "📄 package-lock.json:" && ls -la package-lock.json
        echo "📁 public folder:" && ls -la public/ | head -5
        echo "📄 next.config.mjs:" && ls -la next.config.mjs
        
    - name: Setup Server Environment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          # Clean up existing deployment
          sudo rm -rf /var/www/scrbd-downloader
          sudo mkdir -p /var/www/scrbd-downloader
          sudo npm install -g pm2 || echo "PM2 already installed"
          

# Add this step before the SCP action
    - name: Create deployment directory with proper permissions
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          sudo mkdir -p /var/www/scrbd-downloader
          sudo chown -R ${{ secrets.DIGITALOCEAN_USER }}: /var/www/scrbd-downloader
          sudo chmod -R 755 /var/www/scrbd-downloader
          
    - name: 🚀 Deploy to Digital Ocean
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        source: ".next,package.json,package-lock.json,public,next.config.mjs"
        target: "/var/www/scrbd-downloader/"
        strip_components: 0
        overwrite: true
        

# Add this step after SCP to fix permissions
    - name: Fix permissions after copy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          sudo chown -R ${{ secrets.DIGITALOCEAN_USER }}: /var/www/scrbd-downloader
          sudo chmod -R 755 /var/www/scrbd-downloader
          sudo find /var/www/scrbd-downloader -type d -exec chmod 755 {} \;
          sudo find /var/www/scrbd-downloader -type f -exec chmod 644 {} \;

    - name: ✅ VERIFY COPY - Check if files were copied to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          echo "=== SERVER FILE VERIFICATION ==="
          cd /var/www/scrbd-downloader
          
          echo "📁 Current directory contents:"
          ls -la
          
          if [ -d ".next" ]; then
            echo "✅ .next folder EXISTS on server"
            echo "📊 .next contents:"
            ls -la .next/ | head -10
            echo "Total files in .next: $(find .next -type f 2>/dev/null | wc -l)"
          else
            echo "❌ .next folder MISSING on server!"
            echo "🔍 Searching for .next in current directory:"
            find . -name ".next" -type d 2>/dev/null || echo "No .next folder found anywhere"
            
            # Additional debugging
            echo "🔍 All contents in current directory:"
            find . -maxdepth 2 -type d
            echo "🔍 Hidden files:"
            ls -la | grep "^\."
          fi
          
          echo "📄 Other files check:"
          [ -f "package.json" ] && echo "✅ package.json exists" || echo "❌ package.json missing"
          [ -f "next.config.mjs" ] && echo "✅ next.config.mjs exists" || echo "❌ next.config.mjs missing"
          [ -d "public" ] && echo "✅ public folder exists" || echo "❌ public folder missing"
      
    - name: 🔧 Restart Application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          cd /var/www/scrbd-downloader
          
          echo "=== FINAL DEPLOYMENT CHECK ==="
          
          # Final verification before starting
          if [ ! -d ".next" ]; then
            echo "❌ CRITICAL ERROR: .next folder still missing!"
            echo "Cannot start application without build files"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi
          
          echo "✅ All files verified, proceeding with deployment..."
          
          # Install production dependencies
          echo "📦 Installing production dependencies..."
          npm ci --production --ignore-scripts
          
          # Start/restart the application
          echo "🚀 Starting application..."
          pm2 restart scrbd-downloader || pm2 start npm --name "scrbd-downloader" -- start
          
          # Show final status
          echo "=== DEPLOYMENT STATUS ==="
          pm2 status
          pm2 logs scrbd-downloader --lines 10 --nostream
